wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.5
    start_time: 1671502186.688617
    t:
      1:
      - 1
      - 2
      - 3
      - 41
      - 49
      - 55
      - 63
      2:
      - 1
      - 2
      - 3
      - 41
      - 49
      - 55
      - 63
      3:
      - 1
      - 23
      4: 3.8.5
      5: 0.13.7
      8:
      - 5
